export const REQUIRED_COLOR_ROLES = [
  "canvas",
  "surface",
  "surface-raised",
  "surface-muted",
  "text",
  "text-muted",
  "text-inverse",
  "border",
  "border-strong",
  "accent-role",
  "accent-foreground-role",
  "success",
  "warning",
  "destructive",
  "focus",
  "selection",
  "overlay",
] as const;
