export const testIds = {
  appShell: "app-shell",
  createListButton: "create-list-button",
  sidebarCollapseToggle: "sidebar-collapse-toggle",
  fullWidthCanvas: "full-width-canvas",
  accountMenuTrigger: "account-menu-trigger",
  accountMenuContent: "account-menu-content",
  workspaceAddButton: "workspace-add-button",
  workspaceRow: "workspace-row",
  workspaceDragHandle: "workspace-drag-handle",
  workspaceMenuTrigger: "workspace-menu-trigger",
  workspaceRenameSave: "workspace-rename-save",
  workspaceSelectedIndicator: "workspace-selected-indicator",
  listCard: "list-card",
  listTitle: "list-title",
  listTitleInput: "list-title-input",
  listDragHandle: "list-drag-handle",
  listDropZone: "list-drop-zone",
  createItemInput: "create-item-input",
  listItem: "list-item",
  listItemTitle: "list-item-title",
  itemDragHandle: "item-drag-handle",
  deleteListButton: "delete-list-button",
  viewCreateButton: "view-create-button",
  viewCard: "view-card",
  viewDragHandle: "view-drag-handle",
  tagSelector: "tag-selector",
  saveViewButton: "save-view-button",
} as const;

export type TestId = (typeof testIds)[keyof typeof testIds];
