import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { TRPCReactProvider } from "@/trpc/client";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-montserrat",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} h-full antialiased font-extralight`}
    >
      <body className="min-h-full flex justify-center">
        <TRPCReactProvider>
          {children}
          <Toaster
            toastOptions={{
              classNames: {
                description: "!text-zinc-700"
              }
            }}
          />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
