import { Toaster } from "@/components/ui/sonner";
import { TRPCReactProvider } from "@/trpc/client";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased font-extralight`}
    >
      <body className="min-h-full flex justify-center font-normal">
        <TRPCReactProvider>
          {children}
          <Toaster
            toastOptions={{
              classNames: {
                description: "!text-zinc-700"
              }
            }}
          />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
